### PR TITLE
Review & Cleanup

### PR DESCRIPTION
**Pull request by JamesJeffryes**
4 main changes here:
* Move all specs into a spec directory
* Break up server test by type
* Use dict literal for making the records which I find more readable and is actually faster in python
* Remove duplicate workspace client

**One test currently fails because `test/mock_data/narrative2_object.json` is missing** Probably a forgotten `git add`?

### CODE REVIEW

**Review by scanon — CHANGES_REQUESTED** [review]
I think this is all pretty good.  The only thing I may suggest is to make it so you can still run nosetests from outside the container.  This worked before but may break with how the schema_dir is handled now.

**Comment by JamesJeffryes** [comment]
Hmm. I don't think either version supports running outside the docker container right now. I can strip one down so that it does

**Comment by scanon** [comment]
I'm able to with just a minimal amount of setup...

```
(ni) DOE6989977-2:MiscIndexer canon$ cat set.sh
PATH=/anaconda3/bin:$PATH
source activate ni
export KB_DEPLOYMENT_CONFIG=deploy-local.cfg

(ni) DOE6989977-2:MiscIndexer canon$ cat deploy-local.cfg
[MiscIndexer]
kbase-endpoint = https://ci.kbase.us/services
job-service-url = https://ci.kbase.us/services/userandjobstate
workspace-url = https://ci.kbase.us/services/ws
shock-url = https://ci.kbase.us/services/shock-api
handle-service-url = https://ci.kbase.us/services/handle_service
catalog-service-url = https://ci.kbase.us/services/catalog
srv-wiz-url = https://ci.kbase.us/services/service_wizard
njsw-url = https://ci.kbase.us/services/njs_wrapper
auth-service-url = https://ci.kbase.us/services/auth/api/legacy/KBase/Sessions/Login
auth-service-url-allow-insecure = false

scratch = /kb/module/work/tmp

```

**Comment by JamesJeffryes** [comment]
I'll add a deploy-local.cfg file to the repo. Can you also push in the missing 'narrative2_object.json'?

**Comment by jayrbolton** [comment]
Looks good to me.

**Comment by jayrbolton** [comment]
Want to wait for narrative2_object.json before merging?

**Comment by JamesJeffryes** [comment]
@scanon I going to merge this in but when you get a chance can you add the missing narrative2_object.json from your local repo?

**Pull request merged**
